### ISSUE TITLE
Logo Design Home Control

### ISSUE THREAD

**Issue by zularizal** [andrewgiang/home-control#22]
Hi @andrewgiang , I'm a graphic designer, I want to contribute by creating a free logo for your project. What do you think?

**Comment by andrewgiang** [comment]
@zularizal Sure that would be awesome. I'm planning on creating an alpha version to release soon once I get a few more features in so this is perfect timing.

**Comment by zularizal** [comment]
Okay @andrewgiang , I need time to make it. Before that, I have a question, can you explain a little about the description of this app.

**Comment by andrewgiang** [comment]
@zularizal Sure. Basically this is an android companion app to https://www.home-assistant.io/ which will integrate tightly with native android features such as [shortcuts](https://developer.android.com/guide/topics/ui/shortcuts/), a wearable app, [quick tile toggles](https://android.jlelse.eu/develop-a-custom-tile-with-quick-settings-tile-api-74073e849457), and push notifications.

The user connects the their home assistant server which then allows them to create "Actions" which can then used from their in app dashboard or from launcher shortcuts. (wearable and other integrations are coming later)

Here is a small demo of the app in its current state.
![home-icon-chooser](https://user-images.githubusercontent.com/2236756/50386794-bc574e00-06bb-11e9-90a5-eca51edef1d8.gif)

**Comment by zularizal** [comment]
Hi @andrewgiang , sorry for long reply. This is my design logo for your project. This is inspired by the element of the house and a control. What do you think?
And what about color? A, B or C

If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/50571074-bc013600-0dd2-11e9-96ae-7385320c3fd7.png)

**Comment by andrewgiang** [comment]
Hello @zularizal I like color scheme A and could you tweak the house icon a bit to have a more defined roof?

Thanks! these are looking pretty good.

**Comment by zularizal** [comment]
Do you mean like this?

![bitmap](https://user-images.githubusercontent.com/38547278/50720212-46031480-10db-11e9-9258-8cc3ff1b70f0.png)

**Comment by andrewgiang** [comment]
@zularizal Yeah, but lets stick with the first design concept. Not digging the up arrow look on the new one.

**Comment by zularizal** [comment]
How about this?

![bitmap](https://user-images.githubusercontent.com/38547278/50721061-3ee40280-10eb-11e9-96da-23c074c63052.png)

**Comment by zularizal** [comment]
Okay, wait a minute I'll make a pull request for this.

**Comment by zularizal** [comment]
Hi, I have uploaded the logo / icon files to the drive. 
Check this link. https://drive.google.com/open?id=1dLhsyTyt9BtyJYwP6ukiRcfThf-eanjS

And also I have sent a pull request for you. #25

**Comment by andrewgiang** [comment]
Merged thanks!
